;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/DataAssets/DT_GameplayTag.DT_GameplayTag
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="AnimationLayer.Item.Pistol",DevComment="手槍AL")
+GameplayTagList=(Tag="AnimationLayer.Item.Rifle",DevComment="")
+GameplayTagList=(Tag="AnimationLayer.Item.Unarmed",DevComment="無武裝AL")
+GameplayTagList=(Tag="CameraRig.FirstPerson",DevComment="FPS Camera Rig")
+GameplayTagList=(Tag="CameraRig.ThirdPerson",DevComment="TPS Camera Rig")
+GameplayTagList=(Tag="CameraRig.ThirdPerson.Aim",DevComment="Third Person Aiming  Rig")
+GameplayTagList=(Tag="CameraRig.ThirdPerson.Normal",DevComment="")
+GameplayTagList=(Tag="Item.Default",DevComment="")
+GameplayTagList=(Tag="MessageTag.EffectApplied.AddHealth",DevComment="")

